#!/bin/sh

# This source is part of UnitKit, a unit test framework for Mac OS X 
# development. You can find more information about UnitKit at:
# 
# http://x180.net/Code/UnitKit
# 
# Copyright (c)2004 James Duncan Davidson
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# The use of the Apache License does not indicate that this project is
# affiliated with the Apache Software Foundation.

TITLE="UnitKit"
VERSION="2.0"
DESCRIPTION="A unit test framework for Objective-C"

BASE=`dirname $0`
cd $BASE

# clean out previous builds if any

sudo rm -rf /tmp/UnitKit*

rm -rf UnitKit-*.dmg
rm -rf UnitKit-*.tgz

# clean out previous build stuff

sudo xcodebuild -alltargets clean

# build baby build

sudo xcodebuild -target ukrun -buildstyle Deployment DSTROOT=/tmp/UnitKit.dst install

sudo chown -R root:wheel /tmp/UnitKit.dst
mkdir /tmp/UnitKit-$VERSION
mkdir /tmp/UnitKit-$VERSION/Source
rsync -aq --exclude build --exclude .svn $BASE/* /tmp/UnitKit-$VERSION/Source

mv /tmp/UnitKit-$VERSION/Source/uninstall /tmp/UnitKit-$VERSION
mv /tmp/UnitKit-$VERSION/Source/Samples /tmp/UnitKit-$VERSION
mv /tmp/UnitKit-$VERSION/Source/README.* /tmp/UnitKit-$VERSION
mv /tmp/UnitKit-$VERSION/Source/LICENSE /tmp/UnitKit-$VERSION
mv /tmp/UnitKit-$VERSION/Source/NOTICE /tmp/UnitKit-$VERSION
rm /tmp/UnitKit-$VERSION/Source/makedist

sudo /Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker -build -p /tmp/UnitKit-$VERSION/UnitKit.pkg -f /tmp/UnitKit.dst -r $BASE/Package/Resources/ -i $BASE/Package/Info.plist -d $BASE/Package/Description.plist

hdiutil create -imagekey zlib-level=9 -srcfolder /tmp/UnitKit-$VERSION $TITLE-$VERSION.dmg -volname $TITLE
hdiutil internet-enable -yes $TITLE-$VERSION.dmg

tar -C /tmp -czf $BASE/UnitKit-$VERSION.tgz UnitKit-$VERSION

sudo xcodebuild -alltargets clean

sudo rm -rf /tmp/UnitKit*
